extends: default
ignore: |
  clusters/rackman/flux-system/gotk-components.yaml
rules:
  line-length:
    max: 150
    level: warning
  indentation: disable
  document-start: disable
  empty-lines: disable
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
