---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password-connect
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: connect
      version: "2.4.1"
      sourceRef:
        kind: HelmRepository
        name: 1password-connect
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: 1password-connect
  targetNamespace: external-secrets
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |-
              - op: add
                path: /spec/revisionHistoryLimit
                value: 1
  values:
    connect:
      serviceType: ClusterIP
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-secrets
  targetNamespace: external-secrets
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |-
              - op: add
                path: /spec/revisionHistoryLimit
                value: 1
