---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: 1password-connect
  namespace: flux-system
spec:
  interval: 15m
  url: https://1password.github.io/connect-helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  url: https://charts.external-secrets.io
