apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kube-vip.yaml
- ingress-nginx.yaml
- external-secrets.yaml
- cert-manager.yaml
- longhorn.yaml
- grafana.yaml
- influxdb.yaml
- minio.yaml
- cloudnative-pg.yaml
