---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-realm-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: "keycloak-realm-secrets"
        property: google-client-secret
    - secretKey: KEYCLOAK_OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: "keycloak-realm-secrets"
        property: oauth2-proxy-client-secret
    - secretKey: KEYCLOAK_CLAUDE_CODE_CLIENT_SECRET
      remoteRef:
        key: "keycloak-realm-secrets"
        property: claude-code-client-secret
    - secretKey: KEYCLOAK_GRAFANA_CLIENT_SECRET
      remoteRef:
        key: "keycloak-realm-secrets"
        property: grafana-client-secret
    - secretKey: KEYCLOAK_HOME_ASSISTANT_CLIENT_SECRET
      remoteRef:
        key: "keycloak-realm-secrets"
        property: home-assistant-client-secret
