apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://rackman-longhorn-backups@eu-central-003/"
  credentialSecret: "longhorn-backblaze-credentials"
  pollInterval: "24h0m0s"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: backup
  groups:
    - critical
  retain: 7
  concurrency: 2
  labels: {}
