---
apiVersion: v1
kind: Namespace
metadata:
  name: homerun-system-bridge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homerun-system-bridge
  namespace: homerun-system-bridge
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: homerun-system-bridge
  template:
    metadata:
      labels:
        app: homerun-system-bridge
    spec:
      containers:
        - name: mosquitto-sub
          image: eclipse-mosquitto:2.0.22
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-lc"]
          args:
            - |
              echo "Starting homerun-system-bridge...";
              while true; do
                mosquitto_sub \
                  -h mqtt-mosquitto.mqtt \
                  -p 1883 \
                  -t 'homerun/status' \
                  -t 'homerun/lifecycle' \
                  -q 0 \
                  -R ;
                echo "mosquitto_sub exited; restarting in 2s..." >&2
                sleep 2
              done
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
