apiVersion: monitoring.grafana.com/v1alpha1
kind: Alloy
metadata:
  name: k8s-monitoring-alloy-metrics
  namespace: k8s-monitoring
spec:
  template:
    spec:
      containers:
        - name: alloy-metrics # Must match the container name in your base manifest
          resources:
            limits:
              memory: "512Mi" # The new memory limit
            requests:
              memory: "256Mi" # The new memory request