---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
# Database Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "keycloak-db-credentials"
        property: username
    - secretKey: password
      remoteRef:
        key: "keycloak-db-credentials"
        property: password
---
# Keycloak Admin Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "keycloak-credentials"
        property: username
    - secretKey: password
      remoteRef:
        key: "keycloak-credentials"
        property: password
---
# OAuth2-Proxy Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: "oauth2-proxy-credentials"
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: "oauth2-proxy-credentials"
        property: client-secret
    - secretKey: cookie-secret
      remoteRef:
        key: "oauth2-proxy-credentials"
        property: cookie-secret
    - secretKey: redis-password
      remoteRef:
        key: "oauth2-proxy-credentials"
        property: redis-password
---
# PostgreSQL DB (single instance)
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 300m
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
---
# Keycloak (single instance)
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-rw
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  bootstrapAdmin:
    user:
      secret: keycloak-credentials
  http:
    httpEnabled: true
  hostname:
    hostname: https://sso.clarksons.me
    strict: true
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  additionalOptions: []
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 1Gi
---
# Ingress for Keycloak
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    nginx.org/websocket-services: keycloak
spec:
  tls:
    - hosts:
        - sso.${local_ingress_domain}
  ingressClassName: nginx
  rules:
    - host: sso.${local_ingress_domain}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-service
                port:
                  name: http
---
# OAuth2-Proxy
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  chart:
    spec:
      chart: oauth2-proxy
      version: '10.6.0'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  releaseName: oauth2-proxy
  targetNamespace: keycloak
  interval: 15m
  timeout: 5m
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |-
              - op: add
                path: /spec/revisionHistoryLimit
                value: 1
  values:
    config:
      existingSecret: "oauth2-proxy-credentials"
      cookieName: "oauth2-proxy"
      configFile: |-
        provider="keycloak-oidc"
        provider_display_name="Keycloak"
        redirect_url="https://oauth2.local.clarksons.me/oauth2/callback"
        oidc_issuer_url="https://sso.local.clarksons.me/realms/rackman"
        code_challenge_method="S256"
        http_address="0.0.0.0:4180"
        upstreams="file:///dev/null"
        email_domains=["*"]
        cookie_domains=["clarksons.me"]
        cookie_secure=false
        scope="openid"
        whitelist_domains=["*.clarksons.me"]
        insecure_oidc_allow_unverified_email="true"
        silence_ping_logging=true
        request_logging=true
        standard_logging=true
        reverse_proxy=true
        set_xauthrequest=true
        skip_jwt_bearer_tokens=true
    resources:
      requests:
        memory: 64Mi
        cpu: 50m
      limits:
        memory: 128Mi
        cpu: 200m
    sessionStorage:
      type: redis
      redis:
        clientType: "standalone"
        password: "foo"
    redis-ha:
      enabled: true
      replicas: 1
      persistentVolume:
        enabled: false
      emptyDir: {}
      hardAntiAffinity: false
      redisPassword: "foo"
      redis:
        config:
          min-replicas-to-write: 0
          save: ""
          appendonly: "no"
        terminationGracePeriodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 10
      haproxy:
        enabled: false
      exporter:
        enabled: false
      sysctlImage:
        enabled: false
    initContainers:
      waitForRedis:
        enabled: true
    ingress:
      enabled: true
      className: "nginx"
      pathType: Prefix
      path: /oauth2
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      hosts:
        - oauth2.local.clarksons.me
      tls:
        - hosts:
            - oauth2.local.clarksons.me
