---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "keycloak-db-credentials"
      property: username
  - secretKey: password
    remoteRef:
      key: "keycloak-db-credentials"
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: "keycloak-credentials"
      property: username
  - secretKey: password
    remoteRef:
      key: "keycloak-credentials"
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: "oauth2-proxy-credentials"
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: "oauth2-proxy-credentials"
      property: client-secret
  - secretKey: cookie-secret
    remoteRef:
      key: "oauth2-proxy-credentials"
      property: cookie-secret
  - secretKey: redis-password
    remoteRef:
      key: "oauth2-proxy-credentials"
      property: redis-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-credentials
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  # Number of instances in the cluster
  instances: 2
  # External Database connection
  db:
    vendor: postgres
    host: keycloak-db-rw
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  # Bootstrap admin account
  bootstrapAdmin:
    user:
      secret: keycloak-credentials
  # Enabling HTTP communications
  # Keycloak behing HTTP Proxy closing TLS connections
  http:
    httpEnabled: true
  hostname:
    # Setting hostname
    hostname: https://sso.${local_ingress_domain}
    strict: true
    # Enabling back channel
    backchannelDynamic: true
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  # Do not create ingress
  # TLS options are not supported. Ingress resource to be created separatedly.
  ingress:
    enabled: false
  # Additional Options  
  additionalOptions: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    nginx.org/websocket-services: keycloak
spec:
  tls:
    - hosts:
        - sso.${local_ingress_domain}
         
  ingressClassName: nginx
  rules:
  - host: sso.${local_ingress_domain}
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: keycloak-service
            port:
              name: http
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  values:  
    config:
      existingSecret: "oauth2-proxy-credentials"
        
      cookieName: "oauth2-proxy"
        # Config file
      configFile: |-
        # Provider config
        provider="keycloak-oidc"
        provider_display_name="Keycloak"
        redirect_url="https://oauth2.local.clarksons.me/oauth2/callback"
        oidc_issuer_url="https://sso.local.clarksons.me/realms/rackman"
        code_challenge_method="S256"
        ssl_insecure_skip_verify=true
        # Upstream config
        http_address="0.0.0.0:4180"
        upstreams="file:///dev/null"
        email_domains=["*"]
        cookie_domains=["clarksons.me"]
        cookie_secure=false
        scope="openid"
        whitelist_domains=["*.clarksons.me"]
        insecure_oidc_allow_unverified_email="true"
        silence_ping_logging=true
        request_logging=true
        standard_logging=true
        reverse_proxy=true
        set_xauthrequest=true

    sessionStorage:
      type: redis
      redis:
        existingSecret: oauth2-proxy-credentials
        passwordKey: redis-password

    redis:
      enabled: true
      architecture: standalone
      auth:
        existingSecret: oauth2-proxy-credentials
        existingSecretPasswordKey: redis-password

    ingress:
      enabled: true
      className: "nginx"
      pathType: Prefix
      path: /oauth2
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      hosts:
        - oauth2.local.clarksons.me
      tls:
        - hosts:
            - oauth2.local.clarksons.me

  interval: 15m
  timeout: 5m
  releaseName: oauth2-proxy
  targetNamespace: keycloak

  chart:
    spec:
      chart: oauth2-proxy
      version: '7.18.0'
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system

