apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mqtt.yaml
- home-assistant.yaml
- zigbee2mqtt.yaml
- zigbee2mqtt-exporter.yaml
- flux-kube-state-metrics.yaml
- grafana.yaml
- node-red.yaml
- influxdb.yaml
- minio.yaml
- loki.yaml
- k8s-monitoring.yaml
- keycloak.yaml
- keycloak-realm.yaml
- mimir.yaml
- mqtt-events-bridge.yaml
- ntfy.yaml
- frigate.yaml
- homerun.yaml
- homerun-system-bridge.yaml
- x509-certificate-exporter.yaml
