---
apiVersion: v1
kind: Namespace
metadata:
  name: mimir
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-mimir-credentials 
  namespace: mimir
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: MINIO_ACCESS_KEY_ID
    remoteRef:
      key: "minio-mimir-credentials"
      property: username
  - secretKey: MINIO_SECRET_ACCESS_KEY
    remoteRef:
      key: "minio-mimir-credentials"
      property: password
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: mimir
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled # this is required to prevent flux overwriting the env variable strings
spec:
  chart:
    spec:
      chart: mimir-distributed
      version: "5.7.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: mimir
  targetNamespace: mimir
  values:
    global:
      extraEnvFrom:
        - secretRef:
            name: minio-mimir-credentials
    mimir:
      structuredConfig:
        memberlist:
          cluster_label: "mimir"
          cluster_label_verification_disabled: false
        server:
          log_level: info
          grpc_server_max_recv_msg_size: 104857600
          grpc_server_max_send_msg_size: 104857600
          grpc_server_max_concurrent_streams: 1000
        limits:
          max_label_names_per_series: 120
          max_global_series_per_user: 12000000
          ingestion_burst_size: 200000
          ingestion_rate: 150000
          max_global_series_per_metric: 200000000
          compactor_blocks_retention_period: 24h
        blocks_storage:
          backend: s3
          s3:
            endpoint: "minio.minio.svc.cluster.local:9000"
            access_key_id: ${MINIO_SECRET_ACCESS_KEY}
            secret_access_key: ${MINIO_ACCESS_KEY_ID}
            bucket_name: "mimir"
        compactor:
          compaction_interval: 2h
        query_scheduler:
          max_outstanding_requests_per_tenant: 10000
    ingester:
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      replicas: 2
    distributor:
      extraArgs:
        auth.multitenancy-enabled: false
        log.level: info
      replicas: 1
    compactor:
      replicas: 1
    querier:
      replicas: 2
    query_frontend:
      replicas: 1
    query_scheduler:
      replicas: 1
    store_gateway:
      zoneAwareReplication:
        enabled: false
      replicas: 1
    rollout_operator:
      enabled: false
    ruler:
      enabled: false
    overrides_exporter:
      enabled: false
    alertmanager:
      enabled: false
    minio:
      enabled: false
    metaMonitoring:
      dashboards:
        enabled: false
        annotations:
          grafana_folder: "Mimir"
      serviceMonitor:
        enabled: false