---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: user
    remoteRef:
      key: "minio-root-credentials"
      property: username
  - secretKey: password
    remoteRef:
      key: "minio-root-credentials"
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-loki-credentials
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
  - secretKey: user
    remoteRef:
      key: "minio-loki-credentials"
      property: username
  - secretKey: password
    remoteRef:
      key: "minio-loki-credentials"
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-mimir-credentials
  namespace: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: "${onepassword_vault_name}"
  target:
    creationPolicy: Owner
  data:
    - secretKey: user
      remot

