---
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |

    # MQTT listener
    listener 1883
    protocol mqtt
    allow_anonymous true

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
  namespace: mqtt
  labels:
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/name: mosquitto
  annotations:
    recurring-job-group.longhorn.io/critical: enabled
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-mosquitto
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
spec:
  type: LoadBalancer
  loadBalancerIP: "${mqtt_ip}"
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    - name: websocket
      port: 9090
      targetPort: websocket
      protocol: TCP
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-mosquitto
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: mqtt
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: mqtt
    spec:
      containers:
        - name: mosquitto
          image: "eclipse-mosquitto:2.0.22"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config/
              name: config
            - mountPath: /mosquitto/data/
              name: data
          resources:
            requests:
              memory: "200M"
            limits:
              memory: "200M"
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
